accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'





urlpatterns = [

    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/', AccountDetailView.as_view(), name='detail'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

djangoProject9/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('article/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/',ProfileCreateView.as_view(),name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False) # 문자열이 들어갈 것을 말하고 최대 길이를 255로 지정

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render


# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld

@login_required
def hello_world(request):
    if request.method == 'POST':
        temp = request.POST.get('hello_world_input')
        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()
        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html',
                      context={"hello_world_list": hello_world_list})




class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'accountapp/create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk' : self.object.pk})

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

has_ownership = [login_required,account_ownership_required]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk' : self.object.pk})

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class = 'm-5'>
        <h4>Sign up</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:create' %}" method = 'post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class = 'm-4'>
            <input type="submit"
                   class="'btn btn-dark rounded-pill px-5">
            </div>
        </form>

    </div>

</div>



{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% block content %}
<div class ="text-center mw-500 m-auto">
    <div class ="m-5">
        <h4>Quit</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method = "post">
            {% csrf_token %}
            <div class="m-4">
                <input type="submit" class="btn btn-danger rounded-pill px-5">
            </div>
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mw-500 m-auto">

    <img src="{{ target_user.profile.image.url }}" alt=""
         style="height: 12rem; width: 12rem; width: 12rem; border-radius: 10rem; margin-bottom: 2rem; margin-top: 1rem">


    <h2 sytyle = "font-family: 'NanumSquareB'">
        {{ target_user.profile.nickname }}
            {% if target_user.profile %}
        <a href = "{% url 'profileapp:update' pk=target_user.profile.pk %}"
            class =  'material-icons round_button'>
            edit
        </a>

    </h2>
    {% else %}
    <a href="{% url 'profileapp:create' %}">
        <h2 style = "font-family: 'NanumSquareB'">
            Create Profile
        </h2>
    </a>
    {% endif %}
    <h5 style="margin-bottom: 3rem">
        {{ target_user.profile.message }}

    </h5>
    {% if target_user == user %}
    <div>
        <a href="{% url 'accountapp:update' pk=user.pk %}"
            class='material-icons round_button mx-1'>
            settings
        </a>
        <a href="{% url 'accountapp:delete' pk=user.pk %}"
            class='material-icons round_button mx-1'>
            close
        </a>

    </div>
{% endif %}
</div>



{% endblock %}

accountapp/templates/accountapp/hello_world.html
{%  extends 'base.html' %}

{% block content %}


    <div style=" margin:2rem; text-align: center ">
        <h1>METHOD</h1>

        <form action ="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <input type="text" name="hello_world_input">
            <input type="submit" class="px-5 btn btn-dark rounded-pill">

        </form>

        {% for hello_world in hello_world_list %}
        <h3>{{ hello_world.text }}</h3>
        {% endfor %}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class = 'm-5'>
        <h4>Login</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:login' %}" method = 'post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class = 'm-4'>
            <input type="submit"
                   class="'btn btn-dark rounded-pill px-5">
            </div>
        </form>

    </div>

</div>



{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class = 'm-5'>
        <h4>Update Info</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method = 'post'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class = 'm-4'>
            <input type="submit"
                   class="'btn btn-dark rounded-pill px-5">
            </div>
        </form>

    </div>

</div>



{% endblock %}