accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'





urlpatterns = [

    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/', AccountDetailView.as_view(), name='detail'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),

    path('detail/<int:pk>', ArticleDetailView.as_view(),name='detail'),

    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),

]

djangoProject9/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('article/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)


    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True,null=True)

articleapp/forms.py
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title','image','content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 1

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class = 'm-5'>
        <h4>Create Article</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:create' %}"
              method = 'post' enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class = 'm-4'>
            <input type="submit"
                   class="'btn btn-dark rounded-pill px-5">
            </div>
        </form>

    </div>

</div>



{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class="m-5">
        <h4>Delete Article : {{ target_article.title }}</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}"
              method="post">
            {% csrf_token %}
            <div class="m-5">
                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
            </div>
        </form>
    </div>
</div>


{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}


{% block content %}

    <div class="container text-center">

        <div class="my-5">
            {#     제목 / 글쓴이 / 날짜       #}
            <h1 class="NNS_B">{{ target_article.title }}</h1>
            <h4>{{ target_article.writer.profile.nickname }}</h4>
            <p>{{ target_article.created_at }}</p>
        </div>
        <hr>
        <div class="my-5">
            {#      게시글 내용      #}
            <img src="{{ target_article.image.url }}"
                 alt=""
                 class="article_image">


            <div class ='article_content'>
                {{ target_article.content }}
            </div>

            {% if target_article.writer == user %}
            <div>
                <a href="{% url 'articleapp:update' pk=target_article.pk %}"
                   class="btn btn-success rounded-pill px-5">
                    Update
                </a>
                <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
                   class="btn btn-danger rounded-pill px-5">
                    Delete
                </a>
            </div>
            {% endif %}
        </div>
        <hr>
        <div>
            {#      댓글         #}
        </div>

    </div>


{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <style>

        .container div {
        width: 280px;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1.5rem;
            flex-direction: column;
            box-shadow: 0 0 1rem darkgrey;
        }

        div img{
            width: 100%;
            border-radius: 1rem;
        }

    </style>

    <div class="container my-5">

        {% for article in article_list %}

            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
            <span class = "NNS_B m-2">{{ article.title }}</span>
            </div>

        {% endfor %}

    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

    {% include 'snippets/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
            class="btn btn-dark rounded-pill material-icons">
            brush
        </a>
        <a href="{% url 'articleapp:create' %}"
            class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="text-center mw-500 m-auto">
    <div class = 'm-5'>
        <h4>Update Article</h4>
    </div>
    <div>
        <form action="{% url 'articleapp:update' pk=target_article.pk %}"
              method = 'post' enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class = 'm-4'>
            <input type="submit"
                   class="'btn btn-dark rounded-pill px-5">
            </div>
        </form>

    </div>

</div>



{% endblock %}